<!DOCTYPE html>

<html lang="ja">
<!-- --------------------------------------
head
--------------------------------------- -->
<head>
<meta content="text/html" charset="utf-8" http-equiv="Content-Type" />

<!-- 基準URI -->
<base href="https://elephantech-html-tips-etc.on.drv.tw/HTML_TIPS/">

<!-- スタイルシート -->
<link rel="stylesheet" href="_Assets/CSS/Sytle001.css" type="text/css">

<!-- スクリプト -->
<!-- タイトル表示 -->
<script src="_Assets/MakeTitle.js" type="text/javascript"></script>
<!-- 目次表示 -->
<script src="_Assets/MakeToc_L.js" type="text/javascript"></script>



</head>

<!-- --------------------------------------
body
--------------------------------------- -->
<body>

<!-- ページタイトル(ページ内表示) -->
<span id="title"></span>

<!-- リンク(ホームに戻る) -->
<a href="index.html">ホームに戻る</a><br>

<!-- 出典・関連ページ -->
<h5>出典 :</h5>
<a href="https://qiita.com/eijenson/items/7e9e112e69b37f72353c">try-catch-finally句内のreturnについて - Qiita</a>

<h5>関連 :</h5>
<a href="TIPS/C・C%2B%2B/[C%2B%2B]例外処理.html">[C++]例外処理</a><br>
<a href="TIPS/C Sharp/C%23におけるusing.html">C#におけるusing</a><br>

<!-- 目次 -->
<h5>目次 :</h5>
<div id="toc"></div>

<hr>

<!-- 本文ここから -->

<h2>C#における例外処理</h2>
C#ではC++同様の try - catch 節に加え、finally 節が記述できる。<br>
例外の発生有無によらない共通の最終処理を行わせたい場合は、この finally 節に記述する。<br>
この最終処理は try 節、または catch 節を抜ける直前に実行される。<br>
C#の旧い仕様では獲得した資源(ファイルストリーム、セマフォなど)の解放を finally 節で行うことが一般的であったが、<br>
現在では<a href="TIPS/C Sharp/C%23におけるusing.html">usingステートメント</a>を用いたほうが簡潔に記述できる。

<h2>基本形</h2>
関数 DoSomething() で発生した例外を try 節で捕捉する場合の例。<br>
DoSomething() 内で例外が発生しなかった(正常終了した)場合は、try 節中の以降の処理が実行され、finally 節が実行される。<br>
例外が発生した場合は try 節中の以降の処理はスキップされ、catch 節が実行された後 finally 節が実行される。<br>
すなわち、いずれの場合においても finally 節は実行される。<br>
<img src="_Img/MSVS_DotNet_CSharp/CS_TryCatchFinally/01.png"><br>

<h2>try / catch 節に return を含む場合</h2>
try 節、または catch 節に return を含む場合、<b>finally 節は return 文の直前に実行される</b>。<br>
このため、try / catch 節に return を含む場合、finally 節に return を記述すると、try / catch 節の return は到達できないコードとなる。<br>
これにより例外を握りつぶす( catch 節が最後まで実行されない)可能性があるため、注意が必要。<br>
<img src="_Img/MSVS_DotNet_CSharp/CS_TryCatchFinally/02.png"><br>

<h2>例外の投げなおし</h2>
例外をキャッチし、再度例外をスローしたい場合は、throw 句<b>のみ</b>を記述する。
<div class="code">
<kwd>try</kwd>
{
    :
}
<kwd>catch</kwd> (<knw>Exception</knw> ex)
{
    :

    <cmt>// 例外を投げなおす</cmt>
    <kwd>throw</kwd>;
}
</div>
投げなおした時点のスタックトレース情報が残るため、どこで例外を投げ(なおし)たのかが追跡できる。<br>
下記は誤り。投げなおした時点(最新)の情報が残らない。
<div class="code">
<kwd>try</kwd>
{
    :
}
<kwd>catch</kwd> (<knw>Exception</knw> ex)
{
    :

    <cmt>// 例外を投げなおそうとしているが…</cmt>
    <cmt>// try 節で例外が発生した時点までの情報しか残らない</cmt>
    <kwd>throw</kwd> ex;
}
</div>

<h3>finally 節との組み合わせ</h3>
catch 節で例外を投げなおす場合は、catch 節に return を既述した場合と同様、finally 節を実行後に throw 文を実行する。

<div class="code">
<cmt>// ミューテックスの解放待ち</cmt>
m_Mutex.WaitOne();

<kwd>try</kwd>
{
    Hoge();
}
<kwd>catch</kwd>
{
    <cmt>// 例外を投げなおす</cmt>
    <kwd>throw</kwd>;
}
<kwd>finally</kwd>
{
    <cmt>// ミューテックスの解放</cmt>
    m_Mutex.ReleaseMutex();
}
</div>

上記の例では、例外を投げなおす直前にミューテックスを解放する。

</body>
</html>






